### ISSUE TITLE
"Cannot assign to read only property ..." errors on reload in trailpacks 

### ISSUE THREAD

**Issue by zuker** [trailsjs/trailpack-autoreload#5]
Following errors occur on reload in my current trails set up:

```
error: 
 TypeError: Cannot assign to read only property 'server' of object '#<Object>'
    at HapiTrailpack.configure (node_modules/trailpack-hapi/index.js:38:22)
    at app.after.then (node_modules/trails/lib/trailpack.js:63:26)
```

```
error: 
 TypeError: Cannot assign to read only property 'orm' of object '#<Object>'
    at BookshelfTrailpack.configure (index.js:100:5)
    at app.after.then (node_modules/trails/lib/trailpack.js:63:26)
```

package.json:

```
...
    "trailpack": "^1.0.2",
    "trailpack-autoreload": "^1.0.2",
    "trailpack-core": "1.0.0-beta-6",
    "trailpack-datastore": "^1.0.1",
    "trailpack-footprints": "^1.0.0",
    "trailpack-hapi": "^1.0.1",
    "trailpack-repl": "^1.0.6",
    "trailpack-router": "^1.0.2",
    "trailpack-webpack": "0.0.4",
    "trails": "^1.0.0",
    "trails-controller": "^1.0.0-beta-2",
    "trails-model": "^1.0.0-beta-2",
    "trails-policy": "^1.0.2",
    "trails-service": "^1.0.0-beta-2",
...
```

**Comment by ycpatel813** [comment]
I am also facing same error!
